id: 870f0434e98947c09502872bde57a490
initial_creation_type: ocr
source_metadata:
  volumes:
    d64b0ba268ee4cdca73a2bfc15399503:
      base_file: v092.txt
      image_group_id: I1PD95938
      title: ''
      total_pages: 1484
      volume_number: 93
